name: Publish sax4bpm Package

on:
  release:
    types: [published]
  workflow_dispatch: # This adds the manual trigger

jobs:
  build:   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need
        
    - name: Get release version
      id: get_version
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        else
          echo "RELEASE_VERSION=0.2.0" >> $GITHUB_ENV
        fi
      shell: bash
      
    - name: Print GITHUB_REF
      run: echo "GITHUB_REF=${GITHUB_REF}"
      
    - name: Print GITHUB_REF_tags
      run: echo "tags=${GITHUB_REF#refs/tags/}"  
      
    - name: Debug RELEASE_VERSION
      run: echo "RELEASE_VERSION=${{ env.RELEASE_VERSION }}"

    - name: Update setup.py with release version
      run: |
        sed -i "s/version='.*'/version='${{ env.RELEASE_VERSION }}'/" setup.py
        
    - name: Check setup.py version
      run: cat setup.py
      
    - name: Clean dist directory
      run: rm -rf dist/*

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish package
      if: github.event_name == 'release'
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*
